---
on:
  - push
  - pull_request
name: ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install dependencies
        run: yarn

      - name: build typescript
        run: yarn build
